### ISSUE TITLE
[BUG]: CDN contain an invalid 4.1.2 release

### ISSUE THREAD

**Issue by jehon** [octokit/plugin-retry.js#407] opened 2023-02-27 08:20 UTC
### What happened?

I import from CDN:

`https://cdn.skypack.dev/@octokit/plugin-retry`

But CDN contains:

```
console.warn("[Package Error] \"@octokit/plugin-retry@v4.1.2\" could not be built. 
...
export default null;

```
Looking at the scripts, the build in the github action was successfull, but the uploaded content is invalid.

### Versions

4.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jehon** [comment] 2023-02-27 08:21
That seem critical to me... the package can not be used anymore (using the method described in the docs)

**Comment by wolfy1339** [comment] 2023-03-01 02:04
Duplicate of #405

**Closed** 2023-03-02 08:51 UTC
Labels: Status: Triage, Type: Bug

**Comment by jehon** [comment] 2023-03-03 11:26
@oscard0m
I don't follow up the discussion on this tread...
The online release is still broken and unusable: just check the url: https://cdn.skypack.dev/@octokit/plugin-retry

And look at the code: it really says that the code is not built

Could you at least publish a working release?
