### ISSUE TITLE
[Question] Does wrap hook work now?

### ISSUE THREAD

**Issue by frank-zsy** [octokit/plugin-retry.js#13] opened 2019-03-04 06:14 UTC
When I use this plugin for rest.js, I am not sure whether the wrap hook is working fine or not.

I looked into the code, the before-after-hook does not do specific logic in add.js when kind is wrap and when I add a log in bottleneck's on fail event callback function, when there is a 443 error, the program still throw it out and the log in on fail callback not show as well.

So please help me with this and could you give me a brief how to wrap the requests myself because now I need to wrap them one by one and the access point will change too, I think that is not a good solution.

**Comment by gr2m** [comment] 2019-03-04 16:59
Could you please make a code example that reproduces your problem? RunKit is great for that, here is an example https://runkit.com/gr2m/octokit-rest-js-1206

**Comment by Frankzhaopku** [comment] 2019-03-05 06:30
Is this an example?  https://runkit.com/frankzhaopku/octokit-rest-js-retry , and run this code will encounter an error with multiple query in the url.

**Comment by gr2m** [comment] 2019-03-05 07:07
Thanks, this is very helpful! It looks like the retry plugin is duplicating the query parameters, which causes nock not to recognize it anymore. The first request is 

```
https://api.github.com/?client_id=client_id&client_secret=client_secret
```

but then it becomes 

```
https://api.github.com/?client_id=client_id&client_secret=client_secret&client_id=client_id&client_secret=client_secret&client_id=client_id&client_secret=client_secret&client_id=client_id&client_secret=client_secret
```

I have an idea what it could be, I’ll have a look into it

**Comment by Frankzhaopku** [comment] 2019-03-05 07:24
So the retry does work this way and how about when I write in TypeScript? I didn't find an example and may the failure also related to this bug.

**Comment by Frankzhaopku** [comment] 2019-04-04 03:32
@gr2m An irrelative question here, how does runkit URL rendered like this? As far as I know, this evolves content attachment API which is only provided for GitHub App, so does this repo install any GitHub App provided by runkit?

**Comment by gr2m** [comment] 2019-04-04 03:36
Yes, https://github.com/apps/runkit-notebook

**Comment by Frankzhaopku** [comment] 2019-04-04 03:57
Thx, this is very interesting and I think GitHub App is much more fun than bare robot using API.

**Comment by copperwall** [comment] 2020-09-20 18:18
Hey @gr2m,

I was looking into reproducing this issue on the latest versions of @octokit/rest and @octokit/plugin-retry and I had a couple questions.

It looks like the original issue in rest.js v16.0.0 (I got the package version from the runkit above) happens 
 here https://github.com/octokit/rest.js/blob/v16.0.0/plugins/authentication/before-request.js#L39.

In the current versions of octokit/core.js it looks like auth is either expected to happen by passing a token to Octokit or using an auth strategy like [auth-oauth-app.js](https://github.com/octokit/auth-oauth-app.js). And also it looks like the method used in the runkit uses query params for client_id and client_secret which got deprecated sometime last year. https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters.

Do you think this issue is still actionable, or is it mostly for old behavior from an old version of octokit?

**Comment by gr2m** [comment] 2020-09-20 21:47
A lot has changed since the issue was opened originally. I think it'd be safe to close it. If you like, you could try to reproduce the problem using the latest `@octokit/core` (which `@octokit/rest` is built upon since v17) and `@octokit/auth-oauth-app`, to see if the problem persists in that constellation

> In the current versions of octokit/core.js it looks like auth is either expected to happen by passing a token to Octokit or using an auth strategy like auth-oauth-app.js

`@octokit/core` has auth strategy set to https://github.com/octokit/auth-token.js by default, hence the support for setting the `auth` option to a string.

**Comment by copperwall** [comment] 2020-09-23 21:13
I tried reproducing this with the latest @octokit/core and @octokit/auth-oauth-app and I wasn't able to reproduce the problem. I guess the problem is a little different though because instead of appending the client_secret and client_id to the query params of the request URL, @octokit/auth-oauth-app adds a  basic authorization header with the base64 encoded value of $clientId:$clientSecret (which is the non-deprecated way to do it too).

I can try more, but I think this seems good.

**Comment by gr2m** [comment] 2020-09-24 16:48
Yeah, let's close it, thank you so much Chris!

**Comment by copperwall** [comment] 2020-09-30 20:59
Sounds good! I don't have the ability to close it 🙂 I'll check for something else to work on

**Closed** 2020-10-01 06:19 UTC
Labels: bug
